### ISSUE TITLE
"Warning, range is not a multiple of nbThread"

### ISSUE THREAD

**Issue by djarumlights** [JeanLucPons/BSGS#4]
This may be nothing, but I wanted to check. Using some rather outlandish start/stop numbers, I saw these warnings pop up, but the program continues to run. Is it just info or do I need to slack off my span to prevent possible miscalculation?

in.txt
20000000
000000000000000000000000000000000000000002CE00BB2136A445C71E85BF 
000000000000000000000000000000000000016F14FC2054CD87EE6396B33DF3 
list of keys goes here
---
BSGS v1.1
BabyStep:0x0000000020000000 (2^29.00)
Start:2CE00BB2136A445C71E85BF
Stop :16F14FC2054CD87EE6396B33DF3
Keys :35
Number of CPU thread: 4
BabyStep Thread 0: 0x0000000000000001 -> 0x0000000008000000
BabyStep Thread 2: 0x0000000010000001 -> 0x0000000018000000
BabyStep Thread 3: 0x0000000018000001 -> 0x0000000020000000
BabyStep Thread 1: 0x0000000008000001 -> 0x0000000010000000
[2.04 MKey/s][Cnt 2^29.00][03:15][4864.0MB]
Sort Thread 0: 00000000 -> 00800000
Sort Thread 1: 00800000 -> 01000000
Sort Thread 2: 01000000 -> 01800000
Sort Thread 3: 01800000 -> 02000000
[4.70 MSort/s][Cnt 2^25.00][07s][4864.0MB]
_**Warning, range is not a multiple of nbThread
Warning, range is not a multiple of nbThread*1024**_
GiantStep Thread 1: 5BC75988A18C4AF6CD3B03B3CC
GiantStep Thread 3: 1135070986E62739BDC22CE0FE6
GiantStep Thread 2: B78BE51087F75F4954AEE8E1D9
GiantStep Thread 0: 2CE00BB2136A445C71E85BF
[6.20 MKey/s][Cnt 2^30.18][03:18][4864.0MB]

**Comment by JeanLucPons** [comment]
Hello,
This is a constraint of BSGS.
Consider using https://github.com/JeanLucPons/Kangaroo

**Comment by djarumlights** [comment]
I thought it might be too large a space. Ahh, you have a kangaroo program out now too? Most excellent!
